workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Podfile
        script: |
          cd ios
          echo "platform :ios, '13.0'" > Podfile
          echo "use_frameworks!" >> Podfile
          echo "target 'Runner' do" >> Podfile
          echo "  use_modular_headers!" >> Podfile
          echo "  pod 'Firebase/Core'" >> Podfile
          echo "end" >> Podfile
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - mohxmmd@gmail.com