workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "stable"
      xcode: latest
    scripts:
      - name: Set iOS deployment target
        script: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Add PhoneNumberKit to Podfile
        script: |
          echo "pod 'PhoneNumberKit', '~> 2.0'" >> ios/Podfile
      - flutter pub get
      - flutter build ios --release --no-codesign
