workflows:
  ios-app:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Update iOS Deployment Target
        script: |
          # Update the Podfile to set the minimum iOS deployment target to 13.0
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile

          # Update the Xcode project to set the minimum iOS deployment target to 13.0
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 13.0" ios/Runner/Info.plist

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
