workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "stable"
      xcode: latest
    scripts:
      - name: Clean Flutter and reinstall dependencies
        script: |
          flutter clean
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.podspec
          flutter pub get

      - name: Ensure Podfile has correct platform version
        script: |
          if [ -f ios/Podfile ]; then
            sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/g' ios/Podfile
          else
            echo "platform :ios, '13.0'" > ios/Podfile
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
