workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "stable"
      xcode: latest
    scripts:
      - name: Set iOS deployment target in Podfile
        script: |
          if [ -f ios/Podfile ]; then
            sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/g' ios/Podfile
          else
            echo "platform :ios, '13.0'" > ios/Podfile
          fi

      - name: Clean Flutter and reinstall dependencies
        script: |
          flutter clean
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.podspec
          flutter pub get

      - name: Ensure correct package linking
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod setup
          pod install --verbose --repo-update
          cd ..

      - name: Run Xcode build with extra flags
        script: |
          flutter build ios --release --no-codesign --verbose
