workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "stable"
      xcode: latest
    scripts:
      - name: Set iOS deployment target
        script: |
          # Set iOS deployment target to 13.0
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Add PhoneNumberKit to Podfile
        script: |
          # Add PhoneNumberKit to Podfile
          echo "pod 'PhoneNumberKit', '~> 2.0'" >> ios/Podfile

      - name: Set platform version in Podfile
        script: |
          # Set minimum iOS version in the Podfile to 13.0
          sed -i '' 's/# platform :ios, .*/platform :ios, '13.0'/g' ios/Podfile

      # Install dependencies and build the app
      - flutter pub get
      - flutter clean
      - flutter build ios --release --no-codesign
