workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "stable"
      xcode: latest
    scripts:
      - name: Ensure Flutter iOS directory is set up
        script: |
          flutter pub get
          flutter build ios --no-codesign --simulator # This generates required files
          cd ios
          rm -rf Pods Podfile.lock .symlinks Flutter/Flutter.podspec
          pod install
          cd ..

      - name: Run Xcode build with extra flags
        script: |
          flutter build ios --release --no-codesign --verbose
