workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "stable"
      xcode: latest
    scripts:
      - name: Set up Podfile
        script: |
          if [ ! -f ios/Podfile ]; then
            cat <<EOL > ios/Podfile
          platform :ios, '13.0'
          use_frameworks!
          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
          EOL
          else
            sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/g' ios/Podfile
          fi

      - name: Clean Flutter and reinstall dependencies
        script: |
          flutter clean
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.podspec
          flutter pub get
          cd ios && pod install && cd ..

      - name: Run Xcode build with extra flags
        script: |
          flutter build ios --release --no-codesign --verbose
