workflows:
  ios-app:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: 3.24.5
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean CocoaPods cache & Flutter clean
        script: |
          cd ios
          pod cache clean --all
          flutter clean

      - name: Update Podfile
        script: |
          cd ios
          echo "platform :ios, '13.0'" > Podfile
          echo "" >> Podfile
          echo "target 'Runner' do" >> Podfile
          echo "  # Comment the next line if you don't want to use dynamic frameworks" >> Podfile
          echo "  use_frameworks!" >> Podfile
          echo "" >> Podfile
          echo "  # Pods for Runner" >> Podfile
          echo "  pod 'FirebaseCore', :modular_headers => true" >> Podfile  # Adding FirebaseCore
          echo "" >> Podfile
          echo "  target 'RunnerTests' do" >> Podfile
          echo "    inherit! :search_paths" >> Podfile
          echo "    # Pods for testing" >> Podfile
          echo "  end" >> Podfile
          echo "end" >> Podfile
          cat Podfile  # Print updated Podfile for debugging


      - name: Ensure Dependencies Are Installed
        script: |
          flutter pub get
          cd ios
          pod install --repo-update

      - name: Ensure Firebase Modules Are Found
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..
          flutter clean
          flutter pub get

      - name: Verify GeneratedPluginRegistrant.m
        script: |
          FILE="ios/Runner/GeneratedPluginRegistrant.m"
          if grep -q "firebase_core" "$FILE"; then
            echo "firebase_core module found in GeneratedPluginRegistrant.m"
          else
            echo "Error: firebase_core module not found in GeneratedPluginRegistrant.m"
            exit 1
          fi

      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign || { echo "Retrying build..."; flutter build ipa --release --no-codesign; }

    artifacts:
      - build/ios/archive/*.ipa
