// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7SH8o71UzdH5_0lGSgTcA7BwGoqkvrf8',
    appId: '1:849461771877:web:1b6956bc2a3d7d4acd108c',
    messagingSenderId: '849461771877',
    projectId: 'peak-fb11c',
    authDomain: 'peak-fb11c.firebaseapp.com',
    storageBucket: 'peak-fb11c.firebasestorage.app',
    measurementId: 'G-KDMSD5S6K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASUCI-ukQoSnqwdqgw6dvGmnt9nTHfKSw',
    appId: '1:849461771877:android:0cf82673a7aa3034cd108c',
    messagingSenderId: '849461771877',
    projectId: 'peak-fb11c',
    storageBucket: 'peak-fb11c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgB_2_N2UXw4sLSfgYmaW7KZJSf-CiKY8',
    appId: '1:849461771877:ios:cdfb5a9deb317555cd108c',
    messagingSenderId: '849461771877',
    projectId: 'peak-fb11c',
    storageBucket: 'peak-fb11c.firebasestorage.app',
    iosBundleId: 'com.bluewhyte.peak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgB_2_N2UXw4sLSfgYmaW7KZJSf-CiKY8',
    appId: '1:849461771877:ios:d6f1430f03dae370cd108c',
    messagingSenderId: '849461771877',
    projectId: 'peak-fb11c',
    storageBucket: 'peak-fb11c.firebasestorage.app',
    iosBundleId: 'com.example.peakApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7SH8o71UzdH5_0lGSgTcA7BwGoqkvrf8',
    appId: '1:849461771877:web:1b6956bc2a3d7d4acd108c',
    messagingSenderId: '849461771877',
    projectId: 'peak-fb11c',
    authDomain: 'peak-fb11c.firebaseapp.com',
    storageBucket: 'peak-fb11c.firebasestorage.app',
    measurementId: 'G-KDMSD5S6K6',
  );

}