// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8fo2tbKTVBXdSIiuALtrmmNAKbto2ZsQ',
    appId: '1:689652938526:web:678d759a5ee40cdf5f3b0f',
    messagingSenderId: '689652938526',
    projectId: 'peak-society',
    authDomain: 'peak-society.firebaseapp.com',
    storageBucket: 'peak-society.firebasestorage.app',
    measurementId: 'G-KPW27GYLPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB02zG-8GmBLyxF2X48BLrMEBX-I9zsKe4',
    appId: '1:689652938526:android:15b2555fa3b1b4d75f3b0f',
    messagingSenderId: '689652938526',
    projectId: 'peak-society',
    storageBucket: 'peak-society.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_qgXWuJsxII3wiXamLukhR3Ol5x9bCE',
    appId: '1:689652938526:ios:8fe56c886524696e5f3b0f',
    messagingSenderId: '689652938526',
    projectId: 'peak-society',
    storageBucket: 'peak-society.firebasestorage.app',
    iosBundleId: 'com.bluewhyte.peak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_qgXWuJsxII3wiXamLukhR3Ol5x9bCE',
    appId: '1:689652938526:ios:3f829c9e1eee87d35f3b0f',
    messagingSenderId: '689652938526',
    projectId: 'peak-society',
    storageBucket: 'peak-society.firebasestorage.app',
    iosBundleId: 'com.example.peakApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8fo2tbKTVBXdSIiuALtrmmNAKbto2ZsQ',
    appId: '1:689652938526:web:3e91ecb0c2ad110b5f3b0f',
    messagingSenderId: '689652938526',
    projectId: 'peak-society',
    authDomain: 'peak-society.firebaseapp.com',
    storageBucket: 'peak-society.firebasestorage.app',
    measurementId: 'G-F84NEY8YZ8',
  );

}